### ISSUE TITLE
Automate intial Git clone

### ISSUE THREAD

**Issue by JonasHelming** [openETCS/toolchain#243]
Maybe we should make the first step easier for the user and offer an action on the welcome page, which automatically clones and imports the github project/projects.

**Comment by jastram** [comment]
The underlying product backlog item https://github.com/openETCS/product-backlog/issues/14 has been closed.  Considering how openETCS is used within the project, I'll close this one too, as it is a "nice to have", and we just don't have the resources to implement it.
