### ISSUE TITLE
openETCS License for JRE?

### ISSUE THREAD

**Issue by JonasHelming** [openETCS/toolchain#257]
We made the JRE part of the product and therefore the repo contains a JRE. This cannot be published under EUPL. Do we need to adapt our IP Policy?

**Comment by jastram** [comment]
The underlying product backlog item https://github.com/openETCS/product-backlog/issues/14 has been closed.  Considering how openETCS is used within the project, I'll close this one too, as it is a "nice to have", and we just don't have the resources to implement it.
