### ISSUE TITLE
Need OpenETCS perspectives in Papyrus

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/toolchain#263]
According discussion during SysML training, specific perspectives for the project in papyrus will be useful to develop a model in SysML following a common, methodology.

Objective: limit the number of elements (diagrams, nodes, links,...) which can be used to define the model.

At the beginning at least one perspective can be defined based on description of D2.4 (https://github.com/openETCS/requirements/blob/master/D2.4/D2_4.pdf).

**Comment by jastram** [comment]
The underlying product backlog item https://github.com/openETCS/product-backlog/issues/14 has been closed.  Considering how openETCS is used within the project, I'll close this one too, as it is a "nice to have", and we just don't have the resources to implement it.
