### ISSUE TITLE
Complete problem description for Model Versioning and collaborative work

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#290]
Stakeholders:
- Uwe Steinke

The underlying problem:

- Prevent concurrent editing
- Prevent inconsistent model states
- Prevent corrupt models
- Prevent merge operations in the first place

Possible Solutions:

- Model Store (CDO or EMFStore)
- File-based version system with locking (e.g. Subversion)
- Improve merging (e.g. EMF Compare)
- Break down the models in as many files as possible

**Comment by UweSteinkeFromSiemens** [comment]
No further action required during the remaining duration of the openETCS project. Might be closed.
