### ISSUE TITLE
Provide a model organisation for  Papyrus

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#294]
@UweSteinkeFromSiemens  provides a model structure to do collaborative work with Papyrus see 
https://github.com/openETCS/modeling/tree/master/ModelSpace

**Comment by jastram** [comment]
@UweSteinkeFromSiemens , considering your last comment: Do we still need this at all?  If no, please close.

**Comment by UweSteinkeFromSiemens** [comment]
Since some colleagues at DB are using SysML based on SCADE Suite, I will forward this question to @BerndHekele

**Comment by BerndHekele** [comment]
ince the issue was opened we gained a bit of expierence in handling the models.
I believe, we can close the issue with status quo.
