### ISSUE TITLE
Provide project specific settings

### ISSUE THREAD

**Issue by jfaltermeier** [openETCS/toolchain#322]
In order to improve code quality the same settings regarding the code formatter, clean up actions, save action, compiler warnings, and so on should be used by every programmer. 
Currently there are no specific settings meaning that every developer uses the local workspace settings from his/hers IDE mich may vary. 
The easiest way to do so is to make the settings project-specific and apply them to the existing projects. Developers won't have to adapt their settings, because they come with the project.

**Comment by jastram** [comment]
We have no resources to implement this - closing.
