### ISSUE TITLE
Non-mandatory requirements collection

### ISSUE THREAD

**Issue by stanpinte** [openETCS/toolchain#33]
This issue is used to track all requirements that according to WP2, belong to this WP: they are not WP2 mandatory requirements, they are WP-specific requirements.

+\req{The tool chain shall include support for the following graphical user interface facilities:}
+\subreq{model syntax highlighting and auto-completion, for the parts of the model that are text-based}
+\subreq{graphical representation of Subset-026 braking curves}  
+\subreq{tree-based display of model elements}
+\subreq{model animation and debugging}
+\subreq{perspective management: offer in a single graphical user interface several interconnected views for SRS, model and tests.}
+\req{The tool chain shall provide the following reporting facilities:}
+\subreq{detailed implementation metrics}
+\subreq{detailed traceability reports}
+\subreq{detailed model errors and warnings list}

**Comment by jastram** [comment]
The underlying product backlog item https://github.com/openETCS/product-backlog/issues/14 has been closed.  Considering how openETCS is used within the project, I'll close this one too.
