### ISSUE TITLE
Documentation: Provide high-level overview and terminology

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#330]
Requested by @MarcBehrens : Create a chapter that allow people to communicate efficiently about the toolchain.

@idelatorre : please contact Marc to understand his requirement better and create corresponding content.

**Comment by jastram** [comment]
I created such a chapter: https://github.com/openETCS/toolchain/wiki/Overview#terminology

@MarcBehrens - please add your content, or close this when you're satisfied.

**Comment by MarcBehrens** [comment]
No further requirement, can be closed.
