### ISSUE TITLE
Document the feature/plug-in integration process for developer

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#338]
When added a new feature into the toolchain some information are mandatory

- Name, version ...
- Documentation of the feature (How to use install ...)
- Use cases
- Basic tests to perform after a new build

We also need to document the integration into our platform
- Proposition
- Discussion 
- Accepted version ...

**Comment by jastram** [comment]
As mentioned by @lfronc, this has been done and can be closed.
