### ISSUE TITLE
Document the compatibility constraints to import the openETCS models into SCADE System

### ISSUE THREAD

**Issue by astante** [openETCS/toolchain#372]
Papyrus models can only be used in SCADE System with additional manual steps which is addressed in #371 . However, even if the openETCS model is imported manually, there are issues which prevent using it in SCADE System / Suite.

* SCADE System seems to lack support for Submodels directly. However, I managed to import them by directly editing the SCADE System project files. At first glance it looks fine, however transforming the model to SCADE Suite produces error which say that certain files can't be found. This issue has to be further investigated.
* If the previous problems can't be resolved, it has to be considered to transform the openETCS model into **one** papyrus model, which then is imported. This transformation has to be developed.
* It seems that package imports in UML models (either model or registered package) are not supported by SCADE. We have to be absolutely sure if this feature is missing. I currently write a list of constraints in https://github.com/openETCS/modeling/tree/master/ModelingRules/SysML_Constraints . I haven't found in the documentation and in SCADE System itself a way to import an external package.
* For strange reasons, if in an IBD Blocks with flow ports are created and then connected with each other, SCADE Suite complaints about: `Error: Error 0880: Connector <foo> in class <bar> should not cross hierarchy levels`. This occurs if the model is imported from Papyrus, as well as if this is directly modeled in SCADE System.

I know that certain aspects have to be directly addressed to Esterel, but I thought it is good to have these issues tracked in WP7.

**Comment by jastram** [comment]
@astante - considering that the work mode of WP3 changed, do we still need this?  if not, please close.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [toolchain] Document the compatibility constraints to import the openETCS models into SCADE System (#372)" gesendet am 18.06.2015 10:45:15. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
