### ISSUE TITLE
How to work with often changes of the data dictionnary ?

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#396]
- @MarcBehrens : We need to be able to update the data dictionnary often when working on an interface and this changes should be visible asap for the others users.
- @BerndHekele  agreed
=> registered package is maybe not the best solution at this time
- @astante will present an alternative solution to the registered package.

**Comment by jastram** [comment]
Due to tooling changes in WP3 we decided at the Product Backlog meeting today to abandon this US, as nobody is using the data dictionary implementation.
