### ISSUE TITLE
WP7 Test Plan Review

### ISSUE THREAD

**Issue by idelatorre** [openETCS/toolchain#429]
The Test Plan has been update into the toolchain repository. All  @openETCS/toolchain-committer   are invited to give feedbacks to the test plan.

https://github.com/openETCS/toolchain/blob/master/T7.3/TestPlan/OpenETCS_Toolchain_TestPlan.pdf?raw=true

The Cycle is open for everyone interested in collaborating and the closing date is the 1st of October. In case there are discrepancies or conflicts you want to discuss in a meeting, let me know that adding a comment in this issue,.

Best regards,
Izaskun

**Comment by jastram** [comment]
@idelatorre , is the review complete?  What are the next steps?

**Comment by jastram** [comment]
As @idelatorre has no more resources, I'll close this.
