### ISSUE TITLE
Systerel Review of WP7 Test Plan

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/toolchain#433]
Linked to #429 

- page i : Document approbation table to complete
- §1.3 : No links with assessors ? Test plan can play a role in the qualification process.
- §1;4 : what happens if a tool is transformed or removed ? or its goal/use changes ?
- § 2.1.1 : "partnes" => "partners", 'The fact... it is time consuming" => "The fact... is time consuming"
- §2.1.2 : Unit Tests:
        - Why tolerate only  97 % pass rate of Test Scripts and severity  defects closed , Can this level be acceptable for T3 class tools ?
        - How to  define the criticity level  of the defects ?
        - How to ensure 100%  of code coverage ? Is it pertinent whith the use of the toolchain ? that means tha dead code is not tolerated.
- §2.1.2 : Integration Tests:
        - same comments on 97 % than for Unit Tests
        - what means 80%  of all module for the coverage ? does it means that 20% (1 on 5)  of the modules are not tested  on integration point of view  and other are entirelly tested ? How to manage the balance ? is this acceptable on the T3 clas of tools ?
- §2.1.2 : System/Functionnal/Regression/...  Tests
        - same comments on "97 %"
        -  what means "test scripts executed" in the case of a manual execution ?

**Comment by jastram** [comment]
@idelatorre has this been resolved?  If so, then please close.

**Comment by jastram** [comment]
As there were no further comments, I'll close.
