### ISSUE TITLE
Welcome page make openETCS crashed on Ubuntu 14.04 64 

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#436]
The crash happens when opening the welcome page 
(bug for @faustco  and myself
``` 
# A fatal error has been detected by the Java Runtime Environment:
#  SIGSEGV (0xb) at pc=0x00007f2ddcbaebe9, pid=12815, tid=139835796596480
#
# JRE version: Java(TM) SE Runtime Environment (7.0_67-b01) (build 1.7.0_67-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.65-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libwebkitgtk-1.0.so.0+0x45ebe9]  webkit_web_view_get_type+0x2489
#
```

The libwebkitgk is known to have some problems with eclipse some fixes are:
* set the environment variable to SWT_GTK3= 1
-> this is not working for @faustco 
* add these two lines at the end of the openETCS.ini 
```
-Dorg.eclipse.swt.browser.DefaultType=mozilla
-Dorg.eclipse.swt.browser.XULRunnerPath=/usr/lib/xulrunner
```
-> this makes the welcome page not directly open in the openETCS GUI but with firefox.

Anybody has a better solutions  or same troubles ?

**Comment by jastram** [comment]
As there is a workaround and few users use Linux, I'll close this.
