### ISSUE TITLE
Bugreport: Papyrus StateMachine Transitions throw an error

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/toolchain#438]
Starting a new SysML StateMachine and inserting States and Transition:

trying to edit a transition ends with an error message:

![image](https://cloud.githubusercontent.com/assets/2271821/4676862/335434b4-55e0-11e4-9dfe-c288e2070db2.png)

Impediment: It is not possible to edit a transition.

Can you provide a fix or workaround @MatthieuPERIN?
Are there more informations needed?

Tried out with the current and several older releases of the toolchain on Windows 32 and 64 bit.

**Comment by MatthieuPERIN** [comment]
This is *not* a papyrus issue but an Xtext-related issue.

A previous correction was made by downgrading the Xtext version (see #268 )

Does this error still occurs within the Kepler / Luna toolchain ?

Note: the StateMachine diagrams is not to be used within the toolchain, so this might be not critical.

**Comment by jastram** [comment]
Based on this comment:

> Note: the StateMachine diagrams is not to be used within the toolchain, so this might be not critical. 

I will close this issue.
