### ISSUE TITLE
SysmL2B  UI integration

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#441]
@MatthieuPERIN  oct-20-2014 wrote:

``` 
The code is inside the toolchain but ...as there is no UI integration
 (no contribution to the menu) the  code cannot be executed during 
runtime (during the standard use of the toolchain).

Nothing to worry but someone have to take the time to link the code with the 
Eclipse UI (command, menu contribution and all.)
```
@MERCEmentre do you act on this ?

**Comment by MERCEmentre** [comment]
OK, a first working version is available in this branch: https://github.com/openETCS/toolchain/tree/SysML2B_GUI_integration

**Comment by MERCEmentre** [comment]
On 2015-02-12, @MatthieuPERIN told that he'll try to integrate this branch to Luna version of openETCS.

**Comment by MatthieuPERIN** [comment]
The pom.xml file associated to the plugin 'org.openetcs.sysml2b.transformation' present in 'Branch SysML2B_GUI_integration' is not working and make the build crashes as the pom for 'org.eclipse.acceleo.maven' maven artifact cannot be found anywhere.

@MERCEmentre please try to find a solution as I am stuck and all the solution i have tried so far have failed.

**Comment by MERCEmentre** [comment]
Hello Matthieu,

Le 24/02/2015 13:24, Matthieu PERIN a écrit :
> The pom.xml file associated to the plugin
> 'org.openetcs.sysml2b.transformation' present in 'Branch
> SysML2B_GUI_integration' is not working and make the build crashes as
> the pom for 'org.eclipse.acceleo.maven' maven artifact cannot be found
> anywhere.

Does the following page provide the information you need?

   http://wiki.eclipse.org/Acceleo/Maven

Especially this section:

 
http://wiki.eclipse.org/Acceleo/Maven#Plugin_Management_.28parent_and_children_pom.xml.29

Best regards,
david

**Comment by MatthieuPERIN** [comment]
No. Issue come from the fact that maven build get this error message
```
[WARNING] The POM for org.eclipse.acceleo:maven:jar:3.3.0 is missing, no dependency information available
```

Whatever the ressource I try (infigo, kepler, luna release, org.eclipse or raw.github ....)

**Comment by MERCEmentre** [comment]
Hello Matthieu,

Le 27/02/2015 15:49, Matthieu PERIN a écrit :
> |[WARNING] The POM for org.eclipse.acceleo:maven:jar:3.3.0 is missing, no dependency information available

In following months I see what can I don't, but I'm a total stranger to 
those Java things.

Best regards,
david

**Comment by MERCEmentre** [comment]
@MatthieuPERIN Hello Matthieu! I have been able to run my own version of the SysML to B plug-in under openETCS LUNA. Two modifications needed:
* In the plugin, change "uml2/4.0.0/" URL into "uml2/5.0.0"
* Same modification of URL in the model.uml file of the transformed SysML model

In LUNA, Acceleo is in version 3.5.1. I assume Maven files should be updated accordingly.

**Comment by MERCEmentre** [comment]
I updated needed change for LUNA into SysML2B_GUI_integration branch:
https://github.com/openETCS/toolchain/commit/c10715c852f072dde3f9941ec3d2c6655cb24237

**Comment by MERCEmentre** [comment]
I added more change in the SysML2B_GUI_integrationbranch.

I'll try to build myself the toolchain using Maven. Don't hold your breath. ;-) Any recommendation on Maven version to use? The documentation is rather light on the subject: https://github.com/openETCS/toolchain/wiki/Developer-Documentation#Setting_up_the_development_environment

**Comment by astante** [comment]
I have a running version of your plugin that works fine with the Coffee Example. We will change it a bit so the generated files will be placed in the workspace and not in the eclipse folder.

**Comment by MatthieuPERIN** [comment]
OK, at least we might have a work arround. 

@MERCEmentre 
No specific version of Maven to recommend (I personally have version 3.2.5)
I will try to integrate your modifications Monday to another alpha/beta release

**Comment by MERCEmentre** [comment]
@astante Alexandre, this is great!

@MatthieuPERIN Thanks, keep me informed.

**Comment by MatthieuPERIN** [comment]
I have try the build today ...still the same error about missing maven configuration file pom....

@MERCEmentre Can you just build the java file for your acceleo project and commit them to the git repo (modify the .gitignore file to allow git to trace such files).

**Comment by MERCEmentre** [comment]
The translator is not working in Luna, I opened a dedicated issue for it: #486

**Comment by MERCEmentre** [comment]
Another issue is integration with the build system, see issue #488

**Comment by MERCEmentre** [comment]
Considering the current state of the plug-in in Luna version of Elcipse (see #486), it is not possible to execute directly the plug-in in Eclipse. So the GUI integration is meaningless and we won't integrate it.
