### ISSUE TITLE
Integrate the  Scade API

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#446]
From #420 and the US-Luna-Migration and US-SysML2ScadeSuite, we need to find away to integrate the Scade API.

From, https://github.com/openETCS/toolchain/issues/420#issuecomment-57424971 a good solution will be to have an update site fromEsterel.

We need a confirmation from Esterel.

**Comment by astante** [comment]
Any news regarding this issue? I reassign the issue to @Farhangi as he has contact to Esterel.

**Comment by jastram** [comment]
I believe this is now obsolete, as we have no resources to pursue this approach.
