### ISSUE TITLE
New functionality in Papyrus to obtain data flow list

### ISSUE THREAD

**Issue by jpaniagua** [openETCS/toolchain#448]
We want a new functionality in Papyrus, It was explained to Matthieu Perin.
We want to obtain a list automatically from Papyrus Diagram information.
We have an Internal Block Diagram and we want to obtain automatically the "Data Flow Description" list that is in 6.1 chapter of following document:
https://github.com/openETCS/modeling/blob/master/openETCS%20ArchitectureAndDesign/SecondIteration/openETCSArchitectureAndDesignSpecification.pdf

**Comment by jastram** [comment]
Considering that we changed the toolchain architecture, this issue is now obsolete.
