### ISSUE TITLE
Get Formal license agreement for the Scade API use

### ISSUE THREAD

**Issue by MatthieuPERIN** [openETCS/toolchain#449]
As one of our plugin (SysM to Scade) is linked to Scade API, when embedding it in our toolchain (RCP build in particular) the legal issue of licensing of this source code must be settle.

Todo: 
- [ ] Get an official document that describe and precise the licensing of the Scade API,
- [ ] Check that this License is compatible with EUPL/EPL and our use of the Scade API,
- [ ] Integrate the Scade API license into the build as a link for the SysML to Scade plugin.

**Comment by jastram** [comment]
As we will not work on this tooling any more (no resources), we do not need to resolve this any more. If I am mistaken, please reopen.
