### ISSUE TITLE
Evaluate ReqCycle in Use

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#452]
For traceability mechanism we need to evaluate reqCycle 
- [ ] Create an OpenETCS version with reqCycle
- [ ] Find Partners in WP3 to work together
- [ ] Choose a part of the subset as benchmark (see Moritz mport)
- [ ] Try it
- [ ] Propose a process
- [ ] Take a decision

**Comment by jastram** [comment]
Closing, as this is redundant with #470, and we first have to resolve #471, before we can proceed anyway.
