### ISSUE TITLE
ProR-related issues for ReqIF import

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#457]
For the time being, this is the place to collect issues that @morido encountered for his Word-Import into ReqIF, with respect to the RMF (ProR) component:

- [ ] In Tabellen werden offenbar kein rowspan/colspan unterstützt. Das ist aber laut reqif erlaubt: http://www.w3.org/TR/xhtml-modularization/abstract_modules.html#s_simpletablemodule
- [ ] Bei Farbnamen werden anscheinend nur die 17 Standardnamen (red, blue, yellow, ...) aber nicht die restlichen CSS-Namen unterstützt (http://www.w3.org/TR/css3-color/ ; Standardnamen 4.1; CSS-Namen: 4.3)
- [ ] Ich will "Namespace Defaulting" (http://www.w3.org/TR/REC-xml-names/#defaulting).
- [ ] ProR ist offenbar sehr strikt was die erlaubten Tags. Kann ich das Teil auch irgendwie dazu überreden tags, die es nicht kennt, zu ignorieren? 
- [ ] Weder in der ReqIF spec noch in der XHTML modularization spec habe ich Hinweise gefunden, ob / wie die CSS Style Attribute restringiert sind. Wäre schon ganz nett um dem User irgendwie klar zu machen, dass diese Information durch mein Tool hinzugefügt wurde...).

**Comment by jastram** [comment]
@morido - how many of these are still open issues? If you think they are all resolved ("good enough" at least), then please close this one.

**Comment by morido** [comment]
The most "severe" one is still the row- and colspan. The XHTML-renderer used in ProR's grid does not support them. The XHTML editor does.

Anyhow, I believe this can safely be closed.

**Comment by morido** [comment]
Closed #457

**Comment by morido** [comment]
Apparently, I am lacking permissions to close this issue. Will somebody do this for me, please?

**Comment by jastram** [comment]
Closing - thanks!
