### ISSUE TITLE
Document ReqIF-SysML-Traceability plug-in (Papyrus-side)

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#458]
- [ ] Extend documentation here:
https://github.com/openETCS/toolchain/wiki/User-Documentation#Tracing_Requirements_and_SysML_Models
- [ ] The remainder of this section is outdated, also need to be update.

@MatthieuPERIN takes the lead, @idelatorre supports.

**Comment by MatthieuPERIN** [comment]
Sorry I have no time right now.

I will try to advance on this by the end of Juanary.

**Comment by jastram** [comment]
Closing, as w do have some adequate documentation, and no resources to improve it further.
