### ISSUE TITLE
The custom domain for the openETCS GitHub Pages site is pointed at an outdated IP address

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#460]
Hi Jonas,

Do you have DNS control over the openetcs.org domain?  I got this error message:

> The page build failed with the following error:
> 
> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must take immediate corrective action to ensure that your site remains available after December 1st, 2014. Additional details can be found at https://github.com/blog/1917-github-pages-legacy-ip-deprecation. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages.

> If you have any questions please contact us at https://github.com/contact.

**Comment by astante** [comment]
According to a phone call with @Farhangi the issue is fixed.
