### ISSUE TITLE
Integrate SysML to B documentation into openETCS tool chain doc

### ISSUE THREAD

**Issue by MERCEmentre** [openETCS/toolchain#463]
We should integrate documentation available at https://github.com/openETCS/toolchain/tree/master/ToolDescription/MERCE-SysML-to-B into official openETCS toolchain doc made at https://github.com/openETCS/toolchain/wiki/Documentation .

Question for @idelatorre : the documentation is quite long. Should we create chapters in existing doc (at https://github.com/openETCS/toolchain/wiki/User-Documentation#TODO_SysML_to_B_transformation I guess) or create a new top level doc that would be referenced in the tool chain?

2nd question for @idelatorre : am I correct that I only need to create pages on the wiki (under Documentation) to have it integrated into tool chain documentation? Any other things to do?

**Comment by idelatorre** [comment]
This issue was duplicated. See #440
