### ISSUE TITLE
List of OpenETCS toolchain requirements

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#474]
telco 08.01.2015:
We need a list of the toolchain requirements as part of test plan and to be linked with the test specification of the tool chain.
This lists may comes from
- D2.6 High-level requirements
- Toolchain Architecture https://github.com/openETCS/toolchain/blob/master/T7.3/ToolChainArchitecture/WP7-Toolchain_architecture.pdf
- Tool chain D7.1 Primary tools
- Tool chain D7.2 Secondary tools 
https://github.com/openETCS/toolchain/tree/master/Deliverables

**Comment by cecilebraun** [comment]
The list has been started in the document 
https://github.com/openETCS/toolchain/blob/master/T7.3/ToolChainArchitecture/WP7-Toolchain_architecture.pdf

**Comment by jastram** [comment]
As @idelatorre completed the test plan, this can be closed.
