### ISSUE TITLE
Define OpenETCS toolchain requirements  Unique identifier

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#475]
From the list #474 , we need to have unique way of referencing the requirements for traceability and documentation purpose.

**Comment by morido** [comment]
Does the term "requirement" refer to the contents of an ETCS specification? If so, is everyone ok with using the *tracestring* from #437 for the this purpose?

In this case the issue may be closed.

**Comment by jastram** [comment]
@morido  - I agree with that assessment.  I'll close this.
