### ISSUE TITLE
SysML2B Unit test

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#476]
We need Unit test and/or test specification for the SysML2B plug-in.

**Comment by MERCEmentre** [comment]
ACK.

**Comment by MERCEmentre** [comment]
Currently we don't have a rigorous test bed. We have a big example that we can translate fully and that exercises more or less all of our code. I don't currently know how to specify or improve this current state.

**Comment by MERCEmentre** [comment]
The current technology status does not allow us to make rigorous tests. So we won't provide tests. We only have a prototype demonstrator.
