### ISSUE TITLE
SysML2Scade Unit tests

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#478]
We need Unit test and/or test specification for the SysML2Scade plug-in.

**Comment by jastram** [comment]
@astante - you are the only one qualified to this.  Do you have resources to do this? If not, we'll have to close it due to lack of resources.

**Comment by MERCEmentre** [comment]
I would close thise issue. SysML2B is a research prototype, we have no resource or willing to do unit tests.

**Comment by jastram** [comment]
Thanks - closing.

**Comment by MERCEmentre** [comment]
Oops, I read it as "SysML2B" while in fact it was "SysML2Scade", so maybe @astante should give his opinion. ;-)

**Comment by jastram** [comment]
@astante - what's your thought on this one? Unless you think that we'll produce more unit tests for this, I think it can be closed. Please close if you agree.

**Comment by jastram** [comment]
No response - closing.
