### ISSUE TITLE
Please test alpha release  of the toolchain for Luna version

### ISSUE THREAD

**Issue by MatthieuPERIN** [openETCS/toolchain#482]
The luna version of the toolcahin have it first alpha version.

Please have a look at it and give feedback (remind that it is an alpha version).

https://github.com/openETCS/toolchain/releases/tag/v0.1-alpha

**Comment by astante** [comment]
I will of course try that out to test a bit the functionality for the ITEA review.

**Comment by MatthieuPERIN** [comment]
Th SysML to B UI integration have not bee successful (see #441 for more details) and i will launch a build with the modification from @stante on SysML Constraint (see #376 ) for the alpha 2 version.

**Comment by MatthieuPERIN** [comment]
The alpha 2 version is Up, do not hesitate to try it ... @MariellePetitDoche  if your bug is still present tell me !

https://github.com/openETCS/toolchain/releases/tag/v0.2-alpha

**Comment by MariellePetitDoche** [comment]
I succeed to install the bnew release (linux 64 bits) and to open the old model.
However openning is really slow.

now, is it possible to work and modify my old model (created on Kepler)  or shall I wait ?

**Comment by MatthieuPERIN** [comment]
@MariellePetitDoche , You can edit and modify them in the alpha but keep in mind __that these modified version will not be usable anymore in the Kepler toolchain__

For the performance issue, can you give me your hardware configuration and can somebody else try the 64bit version of the toolchain to have another test ? 

Do your performance issue also present when modelling on a fresh newly created model ?

**Comment by MariellePetitDoche** [comment]
Performance issues are mainly occured at starting, expecially the first time.
Then they are some improvements since my last experiences with the Kepler version.
But maybe it is due to  my pretty new latop (i5-4200H, 2,8 GHz, 8GB of RAM)

**Comment by MatthieuPERIN** [comment]
At first startup eclipse set-up the workspace, translate uml models, load papyrus, etc ... so performance issue can occur here for sure.

Then, as eclipse is really RAM dependent, the 8GB RAM have helped a lot, still I am happy that the toolchain is more operable now :)

**Comment by jastram** [comment]
Migration is complete, so will close this one.
