### ISSUE TITLE
Move Coffee machine example out of toolchain tree

### ISSUE THREAD

**Issue by MERCEmentre** [openETCS/toolchain#483]

**Comment by MERCEmentre** [comment]
See with @idelatorre where to put the example (discussed at 2015-02-12 telco).

**Comment by jastram** [comment]
@MERCEmentre - has there been a comment from @idelatorre ? Should she be assigned or you?  I would like to close this.

**Comment by MERCEmentre** [comment]
No comment from @idelatorre

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [toolchain] Move Coffee machine example out of toolchain tree (#483)" gesendet am 09.06.2015 14:02:53. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by jastram** [comment]
I think @idelatorre is not active any more (out of funds).

 @MERCEmentre - I have no problem leaving this example where it is.  If you agree, let's close this issue.
