### ISSUE TITLE
Utility and uses of the sysml.report plugin

### ISSUE THREAD

**Issue by MatthieuPERIN** [openETCS/toolchain#484]
During my cleaning of the bundles repository I have found a plugin : `org.openetcs.sysml.report`

What is it purpose ?  (seems that it is building something at build)
Should it be included in the build or proposed as a standalone ?

**Comment by astante** [comment]
Maybe @Farhangi can comment on that, because if I recall correctly he wanted to create some reports based on the SysML models.

**Comment by jastram** [comment]
Agree with @astante , @Farhangi seems to be the only one who committed something meaningful here.  I'll assign to him.

**Comment by jastram** [comment]
@Farhangi , if this is dead code, then please simply delete it and close the issue.  Thanks!

**Comment by Farhangi** [comment]
hallo @jastra!  this is dead code. i will delate it.
