### ISSUE TITLE
Clarify information on wiki page of ITEA Review 2015

### ISSUE THREAD

**Issue by MatthieuPERIN** [openETCS/toolchain#485]
Hi, 

In page https://github.com/openETCS/toolchain/wiki/ITEA-Review-preparation-2015, ALL4TECH is said to have worked on ESF (European Safety Framework) ... two strange things:

* CEA is working with ALL4TECH on an ESF project (Eclipse safety Framework), there are 2 separates project or just a typo error ?
* A plugin related to ESF is to be presented ...but there is no such plugin present in the toolchain as far as I know ...

@astante , @lfronc  any ideas ?

**Comment by astante** [comment]
I got the information from Veronique. I think she is not member of the toolchain repository, because she was not able to edit the wiki herself. I will forward your question directly to Veronique.

**Comment by vgontier** [comment]
From Frédérique:
ESF is the Opensource version of Safety Architect.

**Comment by MatthieuPERIN** [comment]
OK, So ESF is _Eclipse Safety Framework_ the project with CEA.

By the way there no ESF related plugin in the toolchain so please correct this in the "plugin to show" list to avoid mistakes :)

**Comment by astante** [comment]
Although there are no plugins right now in the toolchain repository for EFS, I will mention that there is ongoing work on this integration, but currently no plugin available in our toolchain repository.
