### ISSUE TITLE
Provide List of changed files

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#492]
This is a follow-up issue on #487 . @MarcBehrens requested a list of changed files.  Here is a mini-spec for what we intend to do:

1. We will create a second status file (e.g. status-files.txt) and leave the old one running.
2. The underlying mechanism will be the same as specified in #487 .
3. Like the initial implementation, the file will grow, rather than being replaced.
4. The file format is as follows:

## File Format

- 1st Line: Timestamp
- Subsequent lines: filenames, relative to the root of the git repository, one path per line. There will be no encoding, e.g. spaces stay space.  The file is UTF-8 encoded.
- Followed by an empty line

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[toolchain] Provide List of changed files (#492)" gesendet am 09.06.2015 22:59:27. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by jastram** [comment]
This has been realized.
