### ISSUE TITLE
Committer Vote for Ingo Weigelt

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#493]
Please vote +1 for Ingo, to become a committer of the toolchain project, following our [Committer Election Guideline](https://github.com/openETCS/governance/wiki/Committer-Election-Guideline).  Ingo is an employee of Formal Mind and also a committer of the Eclipse Requirements Modeling Framework.  He is currently working on the SysML2B issues encountered with the Luna migration.

**Comment by dalzilio** [comment]
+1

**Comment by jastram** [comment]
+1

**Comment by MERCEmentre** [comment]
:+1:

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [toolchain] Committer Vote for Ingo Weigelt (#493)" gesendet am 19.06.2015 14:58:08. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[toolchain] Committer Vote for Ingo Weigelt (#493)" gesendet am 19.06.2015 11:15:13. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [toolchain] Committer Vote for Ingo Weigelt (#493)" gesendet am 19.06.2015 11:19:52. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [toolchain] Committer Vote for Ingo Weigelt (#493)" gesendet am 19.06.2015 11:35:47. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by astante** [comment]
+1

**Comment by MatthieuPERIN** [comment]
:+1:

**Comment by mahlmann** [comment]
Committer rights granted. Welcome to the team @iweigelt !
