### ISSUE TITLE
Committer Vote for Raphaël Faudou

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#501]
Please vote +1 for Ingo, to become a committer of the toolchain project, following our [Committer Election Guideline](https://github.com/openETCS/governance/wiki/Committer-Election-Guideline).  Raphaël just joined the project to support the traceability activities.

**Comment by jastram** [comment]
:+1:

**Comment by dalzilio** [comment]
:+1:

**Comment by MERCEmentre** [comment]
:+1:

**Comment by iweigelt** [comment]
+1

**Comment by MarcPantel** [comment]
+1

**Comment by MariellePetitDoche** [comment]
+1

**Comment by mahlmann** [comment]
Committer rights have been granted.
