### ISSUE TITLE
Add Acceleo into openETCS toolchain

### ISSUE THREAD

**Issue by MERCEmentre** [openETCS/toolchain#502]
Hello,

I have now a working demonstrator for SysML2B plug-in (https://github.com/openETCS/modeling/tree/master/demo/SysML2B). But I needed to manually include Acceleo plug-ings. Could they be added by default into openETCS toolchain?

Thanks!
david

**Comment by jastram** [comment]
Hi David,

Acceleo is now part of the toolchain.  We don't have a release yet.  Either wait for it, or grab it from Cloudbees: https://openetcs.ci.cloudbees.com/job/openETCS-tycho/lastSuccessfulBuild/artifact/tool/bundles/org.openetcs.releng.products/target/
