### ISSUE TITLE
SysML-to-B / openETCS SysML model

### ISSUE THREAD

**Issue by mahlmann** [openETCS/toolchain#503]
@MERCEmentre 

as far as I know you are working on the SysML-to-B user story and use the "mode and level" model from @MariellePetitDoche for this. With respect to this it might also be worth having a look at the overall openETCS SysML model which has been completed recently. The model is available here:
https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC

Note that the model has been created with SCADE System, which in fact is Papyrus.

**Comment by MERCEmentre** [comment]
Thanks Peter! I downloaded the PDF to read it.

**Comment by jastram** [comment]
@MERCEmentre, can this issue be closed? If so, can you please do it?

**Comment by MERCEmentre** [comment]
Well, it is more a reminder to me than a real issue. It copied it in my own to do list and closing the issue.
