### ISSUE TITLE
Review of Traceability Architecture (ends: 12-Nov-2015)

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#504]
Please review the [traceability architecture document](https://github.com/openETCS/toolchain/raw/master/T7.3/TraceabilityArchitecture/oetc_WP7_traceability.pdf)

Reviewers:
* Marielle
* Jan Welte (?)

Reference: [Review Process](https://github.com/openETCS/governance/raw/master/Review%20Process/OpenETCS_ReviewProcess_0.2.1.pdf)

**Comment by raphaelfaudou** [comment]
Dear all,

I have just read the process review and I wonder if it is not too « formal » for current version of document.
I would like to precise that current document version is « readable » (consistency is ensured) but I still get some questions and elements to refine. 
So document should be seen as an advanced working document and this is probably not the final version. 

I now need support from partners to point out possible misunderstandings of document and answer my pending questions before reaching a final version.
I will post those pending questions soon and I suggest using Thurdsay morning slot to discuss them.

Best 
Raphaël

**Comment by jastram** [comment]
> I have just read the process review and I wonder if it is not too « formal » for current version of document.

I agree - the document was primarily written for the review of deliverables. We should be pragmatic, but we still need to ensure that we have an audit trail.  As long as this is achieved, feel free to simplify.

**Comment by jastram** [comment]
> I will post those pending questions soon and I suggest using Thurdsay morning slot to discuss them.

This is fine with me. As I'll be at EclipseCon, I won't be able to attend.  I'll send an email to that effect, but you need to self-organize.

**Comment by jastram** [comment]
Duplicate of #506 - closing.
