### ISSUE TITLE
Review on " Detailed instructions to use ReqCycle for SysML architecture verification"

### ISSUE THREAD

**Issue by janWelte** [openETCS/toolchain#508]
Review Comments

"openETCS project ReqCycle support for traceability between .reqIF and Papyrus SysML"

- [ ] slide 6 slide references und 1 . and 2. are wrong. Is point 2 shown in this presentation?

- [ ] slide 11 should be Reference requirements (instate of « Rererence requirements » )

- [ ] slide 14 for new user is it not immediately clear how to open the requirements view

- [ ] slide 16 "Load ETCS papyrus SysML model (do not care of Scade profiles for now)" not immediately clear whether the model has to be just opened or loaded as source to reqcycle

further comments will be added later

**Comment by morido** [comment]
@janWelte Can you link the presentation you are talking about? I'm having trouble finding it.

**Comment by raphaelfaudou** [comment]
Hi Moritz,

you can find it here: https://github.com/openETCS/toolchain/tree/master/T7.3/TraceabilityArchitecture/reqCycleUse
It provides instructions to use ReqCycle as means to verify architecture (creation of traceability links between SysML model and .ReqIF requirements)
Jan is currently using this presentation to perform this verification.

Best 
raphaël

**Comment by raphaelfaudou** [comment]
Thanks for first elements of feedback. New revision pushed to repository with all remarks taken into account

**Comment by jastram** [comment]
Closing, as these issues have been incorporated.
