### ISSUE TITLE
Review D7.5 Ecosystem Artifacts (ends 27-Nov-2015)

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#509]
This issue tracks the Review of [D7.5](https://github.com/openETCS/toolchain/raw/master/T7.4/D7.5/WP7-D7.5-Ecosystem_Artefacts.pdf)

* Author: Michael Jastram
* Technical Assessor: Marielle Petit-Doche
* Quality Assessor: Marielle Petit-Doche
* Reviewers: Marielle Petit-Doche, Raphael Faudou

**Comment by raphaelfaudou** [comment]
I m OK to be a reviewer for D7.5: Raphael Faudou

**Comment by jastram** [comment]
Thanks Raphael!

**Comment by raphaelfaudou** [comment]
My remarks on the document:

* 1.1 => « The tool chain implements the development lifecycle defined in 1. 
 => a) reference to D2.3 comes from february 2013: it mentions initial intended process with SSRS and part of this approach has been abandoned so I’m not sure that the tool chain really implements this process.  
 =>     b) There have been two recent updates (june and september 2015) and last one is D2_3a_02.pdf from september 2015.  Perhaps it would be better to reference this last revision?

* 2.6: missing reference => Sections ?? and 3.5.
* 2.7 typo: double « the » in The ecosystem described so far served the the project

* 3.1 It is also acceptable => perhaps explain a little bit what « acceptable » means. Precise that there is compatibility rules between licenses or simply that material under EPL will not violate openETCS license.

* GENERAL: perhaps some screenshots of tools mentioned in 1. would help readers not familiar with those tools: Github, Waffle , Hudson for instance.

**Comment by jastram** [comment]
@raphaelfaudou - thanks for the feedback

- [x] 1.1 => « The tool chain implements the development lifecycle defined in 1. 
 => a) reference to D2.3 comes from february 2013: it mentions initial intended process with SSRS and part of this approach has been abandoned so I’m not sure that the tool chain really implements this process.  
 =>     b) There have been two recent updates (june and september 2015) and last one is D2_3a_02.pdf from september 2015.  Perhaps it would be better to reference this last revision? **(mj) The reference is not even needed for understanding, so I removed it.**

- [x] 2.6: missing reference => Sections ?? and 3.5. **(mj) Fixed**

- [x]  2.7 typo: double « the » in The ecosystem described so far served the the project

- [x]  3.1 It is also acceptable => perhaps explain a little bit what « acceptable » means. Precise that there is compatibility rules between licenses or simply that material under EPL will not violate openETCS license. **(mj) good point, I improved the text.**

- [ ]  GENERAL: perhaps some screenshots of tools mentioned in 1. would help readers not familiar with those tools: Github, Waffle , Hudson for instance. **(mj) Fundamentally, I agree.  However, as we have to complete the review by Friday, personally, I won't get to it.  If you have time to add some pictures, that would be great, but is not strictly necessary.**

**Comment by MariellePetitDoche** [comment]
Quality remark:
-[ ] footnote numbering is hidding a little bit the end of previous word, maybe a latex package to change (it is just to a have a quality remark ! General quality of the document is pretty good !)

Technical remark:
-[ ] §3 looking to https://github.com/openETCS/ecosystem/wiki, some elements are missing in the document: in particular review process
-[ ] Reference to quality plan, which describe how to manage the artefacts is missing. Maybe in section 3.7

**Comment by jastram** [comment]
Regarding footnote numbering, I assume you mean this:

![footnote](https://cloud.githubusercontent.com/assets/745828/11392250/b922a7b8-9358-11e5-8d08-eb8d48fe955b.png)

This is actually caused by a white click frame (no idea why it's set to white in the template). The click frame is only shown in the PDF viewer, but not printed. I'll just leave it as is, as I don't want to touch the template.

**Comment by jastram** [comment]
I added a link to the review process to https://github.com/openETCS/ecosystem/wiki

**Comment by jastram** [comment]
I added the Quality Plan (and also the Test Plan) in Section 3.7.

**Comment by MariellePetitDoche** [comment]
It is ok for me.

**Comment by jastram** [comment]
The review is now concluded, D7.5 has been uploaded to ITEA.
